# Generated by Django 4.1 on 2023-09-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_scan_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='date',
        ),
    ]
