# Generated by Django 4.1 on 2023-10-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0008_plant_remove_machine_manufacture_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
