# Generated by Django 4.1 on 2023-10-10 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0009_alter_line_id_alter_machine_id_alter_plant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='status.line'),
        ),
        migrations.AddField(
            model_name='status',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='status.plant'),
        ),
    ]
