# Generated by Django 4.1 on 2023-10-17 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0010_status_line_status_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_id',
            field=models.CharField(default=None, max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
