# Generated by Django 4.1 on 2023-10-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0011_machine_machine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='tag_id',
            field=models.CharField(default=None, max_length=8, unique=True),
        ),
    ]
